/*
tn.h - tokentypes for the project
date - 2015. 04. 23
made by. ki-yeon
*/
enum tokentypes
{TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TPLUS, TMINUS, TSTAR, TSLASH, TNOT, TMOD, TASSIGN, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TLESS, TGREAT, TLPAREN, TRPAREN, TLBRACKET, TRBRACKET, TLBRACE, TRBRACE, TCOMMA, TSEMICOLON, TIDENT, TNUMBER, NEWLINE, TERROR};